### ISSUE TITLE
LCD pixel density should be added to the BoardConfig as a property

### ISSUE THREAD

**Issue by cmsanta** [android-ia/device-androidia#1]
LCD pixel density should be added to the BoardConfig as a property, otherwise Android complains at runtime with the following message:

10-31 00:49:42.609  9874  9878 E SurfaceFlinger: ro.sf.lcd_density must be defined as a build property

This is also most likely needed to pass CTS.

**Comment by tpalli** [comment]
Isn't surfaceflinger supposed to query dpi from HAL layer, why do we need to hardcode it?

**Comment by txu4** [comment]
The DPI info (xdpi/ydpi) return from HAL is physical one, in Android system, board configure should also provide a logic dpi, which will be used to count the UI layout.  And root user can change the logic dpi w/ "wm density <val>" command 

If the logic dpi is not provided, the xdpi (physical one) will be used.

**Comment by cmsanta** [comment]
@tpalli what @txu4 has said is correct, Android OS has the concept of "virtual" density as oppose to the "real" physical dpi of the device, the OS provides these "virtual" dpi values so that application developers do not have to worry about supporting the many different LCD display resolutions out there when they ship their apps, so rather than enforcing a specific physical dpi for a particular display, Android groups displays with similar DPI values together, that's the main reason that in general Android supports only a few selected dpi values from the Java APIs: 

120 (LDPI)
160 (MDPI)
213 (TVDPI)
240 (HDPI)
360 (XHDPI)
480 (XXHDPI)
640(XXXHDPI)
